# Prometheus Configuration for CryptaNet Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CryptaNet Backend API
  - job_name: 'cryptanet-backend'
    static_configs:
      - targets: ['cryptanet-backend:5004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # CryptaNet Privacy Layer
  - job_name: 'cryptanet-privacy'
    static_configs:
      - targets: ['cryptanet-privacy:5003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # CryptaNet Anomaly Detection
  - job_name: 'cryptanet-anomaly'
    static_configs:
      - targets: ['cryptanet-anomaly:5002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['cryptanet-proxy:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['cryptanet-redis:6379']
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 30s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Alert rules
rule_files:
  - "alert_rules.yml"
